
POLICY_HOLDERS_DATA_CSV_PATH = '../data/fraud_oracle.csv'
CAT_FEAT_2_LAB_BIN_PATH = '../data/cat_feat_2_lab_bin.pkl'

NUMERIC_COLS = [
    'Age',
    'Deductible',
    'DriverRating',
    'RepNumber',
    'FraudFound_P']


# set the modelling parameters
FRAUD_COL = 'FraudFound_P'

# numerical features
NUMERICAL_FEATURES = [
    'Age',
]
# categorical features
CATEGORICAL_FEATURES = [
    'Month',
    'WeekOfMonth',
    'DayOfWeek', 
    'Make',
    'AccidentArea',
    'DayOfWeekClaimed',
    'MonthClaimed',
    'WeekOfMonthClaimed',
    'Sex',
    'MaritalStatus', 
    'Fault', 
    'PolicyType', 
    'VehicleCategory',
    'VehiclePrice',  
    'RepNumber',
    'DriverRating', 
    'Days_Policy_Accident',
    'Days_Policy_Claim', 
    'PastNumberOfClaims', 
    'AgeOfVehicle',
    'AgeOfPolicyHolder', 
    'PoliceReportFiled', 
    'WitnessPresent', 
    'AgentType',
    'NumberOfSuppliments',
    'AddressChange_Claim', 
    'NumberOfCars', 
    'Year',
    'BasePolicy'
]

FINAL_FEATURES = [
    'Month_01Jan',
    'Month_02Feb',
    'Month_03Mar',
    'Month_04Apr',
    'Month_05May',
    'Month_06Jun',
    'Month_07Jul',
    'Month_08Aug',
    'Month_09Sep',
    'Month_10Oct',
    'Month_11Nov',
    'Month_12Dec',
    'WeekOfMonth_1',
    'WeekOfMonth_2',
    'WeekOfMonth_3',
    'WeekOfMonth_4',
    'WeekOfMonth_5',
    'DayOfWeek_Friday',
    'DayOfWeek_Monday',
    'DayOfWeek_Saturday',
    'DayOfWeek_Sunday',
    'DayOfWeek_Thursday',
    'DayOfWeek_Tuesday',
    'DayOfWeek_Wednesday',
    'Make_Accura',
    'Make_BMW',
    'Make_Chevrolet',
    'Make_Dodge',
    'Make_Ferrari',
    'Make_Ford',
    'Make_Honda',
    'Make_Jaguar',
    'Make_Lexus',
    'Make_Mazda',
    'Make_Mecedes',
    'Make_Mercury',
    'Make_Nisson',
    'Make_Pontiac',
    'Make_Porche',
    'Make_Saab',
    'Make_Saturn',
    'Make_Toyota',
    'Make_VW',
    'AccidentArea_Rural',
    'DayOfWeekClaimed_Friday',
    'DayOfWeekClaimed_Monday',
    'DayOfWeekClaimed_Saturday',
    'DayOfWeekClaimed_Sunday',
    'DayOfWeekClaimed_Thursday',
    'DayOfWeekClaimed_Tuesday',
    'DayOfWeekClaimed_Wednesday',
    'MonthClaimed_01Jan',
    'MonthClaimed_02Feb',
    'MonthClaimed_03Mar',
    'MonthClaimed_04Apr',
    'MonthClaimed_05May',
    'MonthClaimed_06Jun',
    'MonthClaimed_07Jul',
    'MonthClaimed_08Aug',
    'MonthClaimed_09Sep',
    'MonthClaimed_10Oct',
    'MonthClaimed_11Nov',
    'MonthClaimed_12Dec',
    'WeekOfMonthClaimed_1',
    'WeekOfMonthClaimed_2',
    'WeekOfMonthClaimed_3',
    'WeekOfMonthClaimed_4',
    'WeekOfMonthClaimed_5',
    'Sex_Female',
    'MaritalStatus_Divorced',
    'MaritalStatus_Married',
    'MaritalStatus_Single',
    'MaritalStatus_Widow',
    'Fault_Policy Holder',
    'PolicyType_Sedan - All Perils',
    'PolicyType_Sedan - Collision',
    'PolicyType_Sedan - Liability',
    'PolicyType_Sport - All Perils',
    'PolicyType_Sport - Collision',
    'PolicyType_Sport - Liability',
    'PolicyType_Utility - All Perils',
    'PolicyType_Utility - Collision',
    'PolicyType_Utility - Liability',
    'VehicleCategory_Sedan',
    'VehicleCategory_Sport',
    'VehicleCategory_Utility',
    'VehiclePrice_20000 to 29000',
    'VehiclePrice_30000 to 39000',
    'VehiclePrice_40000 to 59000',
    'VehiclePrice_60000 to 69000',
    'VehiclePrice_less than 20000',
    'VehiclePrice_more than 69000',
    'RepNumber_1',
    'RepNumber_2',
    'RepNumber_3',
    'RepNumber_4',
    'RepNumber_5',
    'RepNumber_6',
    'RepNumber_7',
    'RepNumber_8',
    'RepNumber_9',
    'RepNumber_10',
    'RepNumber_11',
    'RepNumber_12',
    'RepNumber_13',
    'RepNumber_14',
    'RepNumber_15',
    'RepNumber_16',
    'DriverRating_1',
    'DriverRating_2',
    'DriverRating_3',
    'DriverRating_4',
    'Days_Policy_Accident_1 to 7',
    'Days_Policy_Accident_15 to 30',
    'Days_Policy_Accident_8 to 15',
    'Days_Policy_Accident_more than 30',
    'Days_Policy_Accident_none',
    'Days_Policy_Claim_15 to 30',
    'Days_Policy_Claim_8 to 15',
    'Days_Policy_Claim_more than 30',
    'PastNumberOfClaims_1',
    'PastNumberOfClaims_2 to 4',
    'PastNumberOfClaims_more than 4',
    'PastNumberOfClaims_none',
    'AgeOfVehicle_2 years',
    'AgeOfVehicle_3 years',
    'AgeOfVehicle_4 years',
    'AgeOfVehicle_5 years',
    'AgeOfVehicle_6 years',
    'AgeOfVehicle_7 years',
    'AgeOfVehicle_more than 7',
    'AgeOfVehicle_new',
    'AgeOfPolicyHolder_16 to 17',
    'AgeOfPolicyHolder_18 to 20',
    'AgeOfPolicyHolder_21 to 25',
    'AgeOfPolicyHolder_26 to 30',
    'AgeOfPolicyHolder_31 to 35',
    'AgeOfPolicyHolder_36 to 40',
    'AgeOfPolicyHolder_41 to 50',
    'AgeOfPolicyHolder_51 to 65',
    'AgeOfPolicyHolder_over 65',
    'PoliceReportFiled_No',
    'WitnessPresent_No',
    'AgentType_External',
    'NumberOfSuppliments_1 to 2',
    'NumberOfSuppliments_3 to 5',
    'NumberOfSuppliments_more than 5',
    'NumberOfSuppliments_none',
    'AddressChange_Claim_1 year',
    'AddressChange_Claim_2 to 3 years',
    'AddressChange_Claim_4 to 8 years',
    'AddressChange_Claim_no change',
    'AddressChange_Claim_under 6 months',
    'NumberOfCars_1 vehicle',
    'NumberOfCars_2 vehicles',
    'NumberOfCars_3 to 4',
    'NumberOfCars_5 to 8',
    'NumberOfCars_more than 8',
    'Year_1994',
    'Year_1995',
    'Year_1996',
    'BasePolicy_All Perils',
    'BasePolicy_Collision',
    'BasePolicy_Liability',
    'Age']

CHATBOT_INPUT_CSV_FILEPATH = '../data/sample_input_csv.csv'

CHATBOT_USER_INPUT_FEATURES = [
    'DateAccident',
    'PolicyHolder',
    'PolicyNumber',
    'PoliceReportFiled',
    'Fault',
    'AccidentArea',
    'WitnessPresent']

POLICY_NUMBER_COL = 'PolicyNumber'

MONTH_COL = 'Month'
MONTH_CLAIMED_COL = 'MonthClaimed'

CHATBOT_OUTPUT_CSV_FILEPATH = '../data/sample_output_csv.csv' 

FRAUD_MODEL_PATH = '../models/03_model_training_with_smote/DecisionTreeClassifier.pkl'